server {
    listen 80;
    listen [::]:80;
    server_name namu.design www.namu.design;

    root /var/www/namu/current;
    index index.html;

    location /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
    }

    location = / {
        return 302 /zh/;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
